const KEY='streakquest.v1',BACKUP_KEY='streakquest.v1.backup',MIRROR_KEY='streakquest.v1.mirror',RECOVERY_DB='streakquest-recovery-v1',RECOVERY_STORE='snapshots',MAX_SNAPSHOTS=30,MILESTONES=[3,7,14,30,50,100,365];
const $=s=>document.querySelector(s),today=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const defaults={activities:[],prefs:{sound:true,animations:true,reduced:false},celebrated:{}};
let state=load();
function normalize(data){return {...defaults,...data,activities:Array.isArray(data?.activities)?data.activities:[],prefs:{...defaults.prefs,...(data?.prefs||{})},celebrated:data?.celebrated&&typeof data.celebrated==='object'?data.celebrated:{}}}
function parseStored(raw){try{return raw?normalize(JSON.parse(raw)):null}catch{return null}}
function load(){
 const primary=parseStored(localStorage.getItem(KEY));
 if(primary)return primary;
 const mirror=parseStored(localStorage.getItem(MIRROR_KEY));
 if(mirror){localStorage.setItem(KEY,JSON.stringify(mirror));return mirror}
 const backup=parseStored(localStorage.getItem(BACKUP_KEY));
 if(backup){localStorage.setItem(KEY,JSON.stringify(backup));localStorage.setItem(MIRROR_KEY,JSON.stringify(backup));return backup}
 return structuredClone(defaults)
}
function openRecoveryDB(){return new Promise(resolve=>{if(!('indexedDB'in window))return resolve(null);const req=indexedDB.open(RECOVERY_DB,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(RECOVERY_STORE))db.createObjectStore(RECOVERY_STORE,{keyPath:'id',autoIncrement:true})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>resolve(null)})}
async function addRecoverySnapshot(data,reason='save'){try{if(!data||!Array.isArray(data.activities))return;const db=await openRecoveryDB();if(!db)return;await new Promise(resolve=>{const tx=db.transaction(RECOVERY_STORE,'readwrite');tx.objectStore(RECOVERY_STORE).add({savedAt:new Date().toISOString(),reason,data:normalize(data)});tx.oncomplete=resolve;tx.onerror=resolve});const all=await getRecoverySnapshots();if(all.length>MAX_SNAPSHOTS){const remove=all.slice(0,all.length-MAX_SNAPSHOTS);await new Promise(resolve=>{const tx=db.transaction(RECOVERY_STORE,'readwrite'),store=tx.objectStore(RECOVERY_STORE);remove.forEach(x=>store.delete(x.id));tx.oncomplete=resolve;tx.onerror=resolve})}db.close()}catch{}}
async function getRecoverySnapshots(){try{const db=await openRecoveryDB();if(!db)return[];const rows=await new Promise(resolve=>{const tx=db.transaction(RECOVERY_STORE,'readonly'),req=tx.objectStore(RECOVERY_STORE).getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>resolve([])});db.close();return rows.sort((a,b)=>(a.id||0)-(b.id||0))}catch{return[]}}
async function latestRecoverySnapshot(requireData=true){const rows=await getRecoverySnapshots();for(let i=rows.length-1;i>=0;i--){const d=rows[i]?.data;if(d&&Array.isArray(d.activities)&&(!requireData||d.activities.length))return rows[i]}return null}
async function clearRecoverySnapshots(){try{const db=await openRecoveryDB();if(!db)return;await new Promise(resolve=>{const tx=db.transaction(RECOVERY_STORE,'readwrite'),req=tx.objectStore(RECOVERY_STORE).clear();req.onsuccess=resolve;req.onerror=resolve});db.close()}catch{}}
function save(){
 const raw=JSON.stringify(state),prev=localStorage.getItem(KEY),previous=parseStored(prev);
 if(prev&&prev!==raw){localStorage.setItem(BACKUP_KEY,prev);addRecoverySnapshot(previous,'before-change')}
 localStorage.setItem(KEY,raw);
 localStorage.setItem(MIRROR_KEY,raw);
 addRecoverySnapshot(state,'current');
 updateBackupStatus()
}
function parseDay(s){return new Date(s+'T12:00:00')}
function dayDiff(a,b){return Math.round((parseDay(b)-parseDay(a))/86400000)}
function streak(a){const dates=[...new Set(a.history||[])].sort();if(!dates.length)return 0;let end=dates.length-1;const t=today(),last=dates[end];if(dayDiff(last,t)>1)return 0;let n=1;for(let i=end;i>0;i--){if(dayDiff(dates[i-1],dates[i])===1)n++;else break}return n}
function isDone(a){return (a.history||[]).includes(today())}
function render(){const list=$('#questList'),total=state.activities.length,done=state.activities.filter(isDone).length,pct=total?Math.round(done/total*100):0;
 $('#progressText').textContent=`${done} / ${total} quest${total===1?'':'s'} completed`;$('#progressPct').textContent=pct+'%';$('#progressBar').style.width=pct+'%';
 $('#hero').classList.toggle('active',done>0);$('#hero').classList.toggle('complete',total>0&&done===total);
 $('#heroTitle').textContent=total&&done===total?'DAY SECURED 🔥':done?'Keep it burning.':'Keep the fire alive.';
 $('#heroSub').textContent=total&&done===total?'All quests complete. Come back tomorrow.':total?(done?`${total-done} quest${total-done===1?'':'s'} still waiting for you.`:'Your quests are waiting. Light the first spark.'):'Create your first quest to begin.';
 list.innerHTML=state.activities.map(a=>{const d=isDone(a),s=streak(a);return `<article class="quest ${d?'done':''}" data-id="${a.id}"><button class="check" aria-label="${d?'Undo':'Complete'} ${esc(a.name)}">${d?'✓':'○'}</button><div class="quest-info"><h3>${esc(a.name)}</h3><p>${d?'Streak secured today 🔥':'Keep the streak alive'}${a.reminder?`<span class="reminder">◷ ${a.reminder}</span>`:''}</p></div><div class="streak ${s?'hot':''}"><span class="fire">🔥</span><strong>${s}</strong><small>DAY${s===1?'':'S'}</small></div></article>`}).join('');
 $('#empty').classList.toggle('hidden',total>0);list.classList.toggle('hidden',!total);renderManageQuests();applyMotion()}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toggle(id){const a=state.activities.find(x=>x.id===id);if(!a)return;const t=today();if(isDone(a)){if(!confirm('Undo today’s completion? Your current streak may decrease.'))return;a.history=a.history.filter(x=>x!==t);save();render();toast('Today’s completion undone.');return}
 a.history=[...(a.history||[]),t];save();render();const card=document.querySelector(`[data-id="${id}"]`);card?.classList.add('flash');burst(card);beep();const s=streak(a);toast(`🔥 Streak secured! ${s} day${s===1?'':'s'}`);if(MILESTONES.includes(s)&&!state.celebrated[id+'-'+s]){state.celebrated[id+'-'+s]=true;save();setTimeout(()=>toast(`🏆 ${s} DAY STREAK — ${milestoneText(s)}`),900)}}
function milestoneText(s){return s>=100?'Legendary consistency.':s>=50?'Your consistency is getting dangerous.':s>=30?'A real habit is taking shape.':s>=14?'Two weeks. No accident.':s>=7?'One week conquered.':'The spark is catching.'}
function burst(el){if(!state.prefs.animations||state.prefs.reduced||!el)return;const r=el.getBoundingClientRect();for(let i=0;i<10;i++){const p=document.createElement('i');p.className='particle';p.textContent=i%2?'✦':'🔥';p.style.left=(r.left+r.width*.8)+'px';p.style.top=(r.top+r.height/2)+'px';p.style.setProperty('--x',(Math.random()*100-50)+'px');p.style.setProperty('--y',(-30-Math.random()*80)+'px');$('#particles').append(p);setTimeout(()=>p.remove(),900)}}
let audio;function beep(){if(!state.prefs.sound)return;try{audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.setValueAtTime(520,audio.currentTime);o.frequency.exponentialRampToValueAtTime(820,audio.currentTime+.09);g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.13);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.13)}catch{}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)}
function applyMotion(){document.body.classList.toggle('no-motion',!state.prefs.animations||state.prefs.reduced)}
$('#addBtn').onclick=$('#emptyAdd').onclick=()=>{$('#questForm').reset();$('#questDialog').showModal();setTimeout(()=>$('#questName').focus(),100)};
$('#settingsBtn').onclick=()=>{syncSettings();updateBackupStatus();$('#settingsDialog').showModal()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
$('#questForm').onsubmit=e=>{e.preventDefault();const name=$('#questName').value.trim();if(!name)return;state.activities.push({id:crypto.randomUUID?.()||String(Date.now()),name,reminder:$('#questReminder').value,history:[],created:today()});save();$('#questDialog').close();render();toast('Quest started. First flame awaits 🔥')};
$('#questList').onclick=e=>{const card=e.target.closest('.quest');if(card&&e.target.closest('.check'))toggle(card.dataset.id)};
let editingQuestId=null,deletingQuestId=null;
function renderManageQuests(){const list=$('#manageQuestList'),empty=$('#manageEmpty');if(!list||!empty)return;empty.classList.toggle('hidden',state.activities.length>0);list.innerHTML=state.activities.map(a=>`<div class="manage-item" data-manage-id="${a.id}"><div class="manage-name"><b>${esc(a.name)}</b><small>${streak(a)} day streak${a.reminder?` · Reminder ${a.reminder}`:''}</small></div><div class="manage-actions"><button class="manage-btn rename" type="button">Rename</button><button class="manage-btn delete" type="button">Delete</button></div></div>`).join('')}
$('#manageQuestList').onclick=e=>{const row=e.target.closest('.manage-item');if(!row)return;const a=state.activities.find(x=>x.id===row.dataset.manageId);if(!a)return;if(e.target.closest('.rename')){editingQuestId=a.id;$('#renameName').value=a.name;$('#renameDialog').showModal();setTimeout(()=>{$('#renameName').focus();$('#renameName').select()},80)}if(e.target.closest('.delete')){deletingQuestId=a.id;$('#deleteCopy').textContent=`Delete “${a.name}”? Its full streak and completion history will be permanently removed.`;$('#deleteDialog').showModal()}};
$('#renameForm').onsubmit=e=>{e.preventDefault();const a=state.activities.find(x=>x.id===editingQuestId),name=$('#renameName').value.trim();if(!a||!name)return;a.name=name;save();$('#renameDialog').close();render();toast('Quest renamed ✓');editingQuestId=null};
$('#cancelDelete').onclick=()=>{deletingQuestId=null;$('#deleteDialog').close()};
$('#confirmDelete').onclick=()=>{if(!deletingQuestId)return;state.activities=state.activities.filter(x=>x.id!==deletingQuestId);Object.keys(state.celebrated||{}).filter(k=>k.startsWith(deletingQuestId+'-')).forEach(k=>delete state.celebrated[k]);save();deletingQuestId=null;$('#deleteDialog').close();render();toast('Quest deleted.')};
function syncSettings(){const supported='Notification'in window;$('#notifyStatus').textContent=!supported?'Not supported in this browser':`Permission: ${Notification.permission}`;$('#permissionBtn').disabled=!supported||Notification.permission==='granted';$('#permissionBtn').textContent=supported&&Notification.permission==='granted'?'Enabled':'Enable';$('#soundToggle').checked=state.prefs.sound;$('#animationToggle').checked=state.prefs.animations;$('#reducedToggle').checked=state.prefs.reduced}
async function updateBackupStatus(){const el=$('#backupStatus'),btn=$('#restoreBackup');if(!el||!btn)return;const backup=parseStored(localStorage.getItem(BACKUP_KEY)),snap=await latestRecoverySnapshot(true);btn.disabled=!(backup||snap);if(backup)el.textContent='Previous local snapshot available. Automatic recovery snapshots are also active.';else if(snap)el.textContent=`Recovery snapshot available from ${new Date(snap.savedAt).toLocaleString()}.`;else el.textContent='Automatic recovery snapshots are active. Export a file for an extra off-device backup.'}
$('#exportBackup').onclick=()=>{const payload={app:'StreakQuest',version:1,exportedAt:new Date().toISOString(),data:state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`streakquest-backup-${today()}.json`;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url);toast('Backup exported ✓')};
$('#importBackup').onclick=()=>$('#importFile').click();
$('#importFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text()),incoming=normalize(parsed?.data||parsed);if(!Array.isArray(incoming.activities))throw new Error('Invalid');if(!confirm('Import this backup? It will replace the current quests on this device.'))return;await addRecoverySnapshot(state,'before-import');const current=localStorage.getItem(KEY);if(current)localStorage.setItem(BACKUP_KEY,current);state=incoming;localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(MIRROR_KEY,JSON.stringify(state));await addRecoverySnapshot(state,'imported');render();updateBackupStatus();toast('Backup restored ✓')}catch{toast('That backup file could not be read.')}finally{e.target.value=''}};
$('#restoreBackup').onclick=async()=>{const local=parseStored(localStorage.getItem(BACKUP_KEY)),snap=local?null:await latestRecoverySnapshot(true),backup=local||snap?.data;if(!backup)return;if(!confirm('Restore the previous recovery snapshot? Your current state will be kept as a fallback copy.'))return;await addRecoverySnapshot(state,'before-restore');const current=localStorage.getItem(KEY);if(current)localStorage.setItem(MIRROR_KEY,current);state=normalize(backup);localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(MIRROR_KEY,JSON.stringify(state));await addRecoverySnapshot(state,'restored');render();updateBackupStatus();toast('Recovery snapshot restored ✓')};
$('#permissionBtn').onclick=async()=>{if(!('Notification'in window))return;const p=await Notification.requestPermission();syncSettings();toast(p==='granted'?'Notifications enabled 🔥':'Notification permission not enabled.')};
$('#notifyBtn').onclick=()=>{if('Notification'in window&&Notification.permission==='granted')new Notification('StreakQuest 🔥',{body:'Your quests are waiting. Keep the fire alive.',icon:'icon.svg'});else{$('#settingsDialog').showModal();syncSettings()}};
['sound','animation','reduced'].forEach(k=>$('#'+k+'Toggle').onchange=e=>{state.prefs[k==='animation'?'animations':k]=e.target.checked;save();applyMotion()});
$('#resetAll').onclick=async()=>{if(confirm('Reset ALL StreakQuest data? This cannot be undone.')){localStorage.removeItem(KEY);localStorage.removeItem(BACKUP_KEY);localStorage.removeItem(MIRROR_KEY);await clearRecoverySnapshots();state=structuredClone(defaults);$('#settingsDialog').close();render();updateBackupStatus();toast('Fresh start. Your flame is waiting.')}};
async function initRecoveryProtection(){const primary=localStorage.getItem(KEY);if(!primary&&state.activities.length===0){const snap=await latestRecoverySnapshot(true);if(snap?.data?.activities?.length){state=normalize(snap.data);const raw=JSON.stringify(state);localStorage.setItem(KEY,raw);localStorage.setItem(MIRROR_KEY,raw);render();toast('Recovered your quests from a safety snapshot 🔥');return}}if(state.activities.length)await addRecoverySnapshot(state,'startup');updateBackupStatus()}
if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
window.addEventListener('pagehide',()=>{if(state.activities.length)addRecoverySnapshot(state,'pagehide')});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(state.activities.length)addRecoverySnapshot(state,'hidden')}else render()});render();initRecoveryProtection();