const KEY='streakquest.v1',MILESTONES=[3,7,14,30,50,100,365];
const $=s=>document.querySelector(s),today=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const defaults={activities:[],prefs:{sound:true,animations:true,reduced:false},celebrated:{}};
let state=load();
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}'),prefs:{...defaults.prefs,...(JSON.parse(localStorage.getItem(KEY)||'{}').prefs)}}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function parseDay(s){return new Date(s+'T12:00:00')}
function dayDiff(a,b){return Math.round((parseDay(b)-parseDay(a))/86400000)}
function streak(a){const dates=[...new Set(a.history||[])].sort();if(!dates.length)return 0;let end=dates.length-1;const t=today(),last=dates[end];if(dayDiff(last,t)>1)return 0;let n=1;for(let i=end;i>0;i--){if(dayDiff(dates[i-1],dates[i])===1)n++;else break}return n}
function isDone(a){return (a.history||[]).includes(today())}
function render(){const list=$('#questList'),total=state.activities.length,done=state.activities.filter(isDone).length,pct=total?Math.round(done/total*100):0;
 $('#progressText').textContent=`${done} / ${total} quest${total===1?'':'s'} completed`;$('#progressPct').textContent=pct+'%';$('#progressBar').style.width=pct+'%';
 $('#hero').classList.toggle('active',done>0);$('#hero').classList.toggle('complete',total>0&&done===total);
 $('#heroTitle').textContent=total&&done===total?'DAY SECURED 🔥':done?'Keep it burning.':'Keep the fire alive.';
 $('#heroSub').textContent=total&&done===total?'All quests complete. Come back tomorrow.':total?(done?`${total-done} quest${total-done===1?'':'s'} still waiting for you.`:'Your quests are waiting. Light the first spark.'):'Create your first quest to begin.';
 list.innerHTML=state.activities.map(a=>{const d=isDone(a),s=streak(a);return `<article class="quest ${d?'done':''}" data-id="${a.id}"><button class="check" aria-label="${d?'Undo':'Complete'} ${esc(a.name)}">${d?'✓':'○'}</button><div class="quest-info"><h3>${esc(a.name)}</h3><p>${d?'Streak secured today 🔥':'Keep the streak alive'}${a.reminder?`<span class="reminder">◷ ${a.reminder}</span>`:''}</p></div><div class="streak ${s?'hot':''}"><span class="fire">🔥</span><strong>${s}</strong><small>DAY${s===1?'':'S'}</small></div></article>`}).join('');
 $('#empty').classList.toggle('hidden',total>0);list.classList.toggle('hidden',!total);renderManageQuests();applyMotion()}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toggle(id){const a=state.activities.find(x=>x.id===id);if(!a)return;const t=today();if(isDone(a)){if(!confirm('Undo today’s completion? Your current streak may decrease.'))return;a.history=a.history.filter(x=>x!==t);save();render();toast('Today’s completion undone.');return}
 a.history=[...(a.history||[]),t];save();render();const card=document.querySelector(`[data-id="${id}"]`);card?.classList.add('flash');burst(card);beep();const s=streak(a);toast(`🔥 Streak secured! ${s} day${s===1?'':'s'}`);if(MILESTONES.includes(s)&&!state.celebrated[id+'-'+s]){state.celebrated[id+'-'+s]=true;save();setTimeout(()=>toast(`🏆 ${s} DAY STREAK — ${milestoneText(s)}`),900)}}
function milestoneText(s){return s>=100?'Legendary consistency.':s>=50?'Your consistency is getting dangerous.':s>=30?'A real habit is taking shape.':s>=14?'Two weeks. No accident.':s>=7?'One week conquered.':'The spark is catching.'}
function burst(el){if(!state.prefs.animations||state.prefs.reduced||!el)return;const r=el.getBoundingClientRect();for(let i=0;i<10;i++){const p=document.createElement('i');p.className='particle';p.textContent=i%2?'✦':'🔥';p.style.left=(r.left+r.width*.8)+'px';p.style.top=(r.top+r.height/2)+'px';p.style.setProperty('--x',(Math.random()*100-50)+'px');p.style.setProperty('--y',(-30-Math.random()*80)+'px');$('#particles').append(p);setTimeout(()=>p.remove(),900)}}
let audio;function beep(){if(!state.prefs.sound)return;try{audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.setValueAtTime(520,audio.currentTime);o.frequency.exponentialRampToValueAtTime(820,audio.currentTime+.09);g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.13);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.13)}catch{}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)}
function applyMotion(){document.body.classList.toggle('no-motion',!state.prefs.animations||state.prefs.reduced)}
$('#addBtn').onclick=$('#emptyAdd').onclick=()=>{$('#questForm').reset();$('#questDialog').showModal();setTimeout(()=>$('#questName').focus(),100)};
$('#settingsBtn').onclick=()=>{syncSettings();$('#settingsDialog').showModal()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
$('#questForm').onsubmit=e=>{e.preventDefault();const name=$('#questName').value.trim();if(!name)return;state.activities.push({id:crypto.randomUUID?.()||String(Date.now()),name,reminder:$('#questReminder').value,history:[],created:today()});save();$('#questDialog').close();render();toast('Quest started. First flame awaits 🔥')};
$('#questList').onclick=e=>{const card=e.target.closest('.quest');if(card&&e.target.closest('.check'))toggle(card.dataset.id)};
let editingQuestId=null,deletingQuestId=null;
function renderManageQuests(){const list=$('#manageQuestList'),empty=$('#manageEmpty');if(!list||!empty)return;empty.classList.toggle('hidden',state.activities.length>0);list.innerHTML=state.activities.map(a=>`<div class="manage-item" data-manage-id="${a.id}"><div class="manage-name"><b>${esc(a.name)}</b><small>${streak(a)} day streak${a.reminder?` · Reminder ${a.reminder}`:''}</small></div><div class="manage-actions"><button class="manage-btn rename" type="button">Rename</button><button class="manage-btn delete" type="button">Delete</button></div></div>`).join('')}
$('#manageQuestList').onclick=e=>{const row=e.target.closest('.manage-item');if(!row)return;const a=state.activities.find(x=>x.id===row.dataset.manageId);if(!a)return;if(e.target.closest('.rename')){editingQuestId=a.id;$('#renameName').value=a.name;$('#renameDialog').showModal();setTimeout(()=>{$('#renameName').focus();$('#renameName').select()},80)}if(e.target.closest('.delete')){deletingQuestId=a.id;$('#deleteCopy').textContent=`Delete “${a.name}”? Its full streak and completion history will be permanently removed.`;$('#deleteDialog').showModal()}};
$('#renameForm').onsubmit=e=>{e.preventDefault();const a=state.activities.find(x=>x.id===editingQuestId),name=$('#renameName').value.trim();if(!a||!name)return;a.name=name;save();$('#renameDialog').close();render();toast('Quest renamed ✓');editingQuestId=null};
$('#cancelDelete').onclick=()=>{deletingQuestId=null;$('#deleteDialog').close()};
$('#confirmDelete').onclick=()=>{if(!deletingQuestId)return;state.activities=state.activities.filter(x=>x.id!==deletingQuestId);Object.keys(state.celebrated||{}).filter(k=>k.startsWith(deletingQuestId+'-')).forEach(k=>delete state.celebrated[k]);save();deletingQuestId=null;$('#deleteDialog').close();render();toast('Quest deleted.')};
function syncSettings(){const supported='Notification'in window;$('#notifyStatus').textContent=!supported?'Not supported in this browser':`Permission: ${Notification.permission}`;$('#permissionBtn').disabled=!supported||Notification.permission==='granted';$('#permissionBtn').textContent=supported&&Notification.permission==='granted'?'Enabled':'Enable';$('#soundToggle').checked=state.prefs.sound;$('#animationToggle').checked=state.prefs.animations;$('#reducedToggle').checked=state.prefs.reduced}
$('#permissionBtn').onclick=async()=>{if(!('Notification'in window))return;const p=await Notification.requestPermission();syncSettings();toast(p==='granted'?'Notifications enabled 🔥':'Notification permission not enabled.')};
$('#notifyBtn').onclick=()=>{if('Notification'in window&&Notification.permission==='granted')new Notification('StreakQuest 🔥',{body:'Your quests are waiting. Keep the fire alive.',icon:'icon.svg'});else{$('#settingsDialog').showModal();syncSettings()}};
['sound','animation','reduced'].forEach(k=>$('#'+k+'Toggle').onchange=e=>{state.prefs[k==='animation'?'animations':k]=e.target.checked;save();applyMotion()});
$('#resetAll').onclick=()=>{if(confirm('Reset ALL StreakQuest data? This cannot be undone.')){localStorage.removeItem(KEY);state=structuredClone(defaults);$('#settingsDialog').close();render();toast('Fresh start. Your flame is waiting.')}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
document.addEventListener('visibilitychange',()=>{if(!document.hidden)render()});render();